### ISSUE TITLE
Team contract

### ISSUE THREAD

**Issue by MDSFusionist** [UBC-MDS/DSCI522-Group10#4]
Dear Team,

Just a gentle reminder to please review the team contract in the google document. Also, a big thank you to Joel for putting together the contract. Your effort in drafting this document is greatly appreciated and lays a solid foundation for our collaboration.

https://docs.google.com/document/d/1Nph3cBnTHiQIvxtCNvm7EylXm3YxGf9JTgV_IeymVUo/edit#heading=h.1socs0ps4n0e

Doris

**Comment by sandygross** [comment]
Thank you, Doris! I think this contract contains all the most important aspects of our group work should look like. Great job. I signed it.

**Comment by joeywwwu** [comment]
Thanks, Doris, I also think it's a great contract already, I will sign it!

**Comment by hema2022ubc** [comment]
Thanks  Doris! I signed it!

**Comment by MDSFusionist** [comment]
Great! We have done with the contract. I will make a pdf file and submit to grapescope later.
