### ISSUE TITLE
Citation in Introduction

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/DSCI522-Group10#7]
Hi @hema2022ubc , 

could you please update the introduction part by adding the citation instead of the links?
Would be great!

**Comment by hema2022ubc** [comment]
Thank you @sandygross ! I modify the format as your suggestion to the APA standard and push the change in the `diss` branch, and you can check whether it is appropriate.

**Comment by hema2022ubc** [comment]
Thank you for the suggesetion and the modification, now the format of references are consistent.
