### ISSUE TITLE
Finished final report file

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/DSCI522-Group10#8]
Dear team, I have just merged our parts and created our Final Report file and added an html Version of it. I also changed part of the discussion part. So let me please know what you think! Additionally, I updated the environment so that it looks like how it is required.
Please react to this message so that I know whether we can merge it to main.

**Comment by joeywwwu** [comment]
The final report looks great! The discussion part feels more comprehensive!

**Comment by MDSFusionist** [comment]
I have reviewed the final report. It looks very concrete to me! Thanks for putting all the parts together @sandygross. Please proceed to merge into the main branch.

**Comment by hema2022ubc** [comment]
It looks good to me!  Also agree proceed to merge into the main branch, so I will close this issue since it is finished.
